import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import Navbar from "./ui/NavBar"
import Footer from "./ui/Footer"
import AOSProvider from "./AOSProvider";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
// @ts-ignore

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/
 
export const metadata: Metadata = {
  title: {
    template: '%s | McGill Aerial Design',
    default: 'McGill Aerial Design',
  },
  description: 'McGill Aerial Design is an EUS design team of 100+ students aiming to promote vertical take-off and landing technologies within McGill University. We strive to prepare keen students for upcoming innovations by expanding our knowledge in the field and creating opportunities. We aim to bring together industry and academia by promoting research about vertical flight technologies, participating in national and international design competitions, and creating workshops that will inspire students.',
  metadataBase: new URL('https://www.mcgillaerialdesign.com/'),
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>)
{

  return (
    <html lang="en">
      <body>
        <AOSProvider />
        <Navbar />
        {children}
        <Footer />
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
